services:
  - type: web
    name: foxfuel-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true

  - type: web
    name: foxfuel-frontend
    env: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
